# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: In-a-petri-dish
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
url: "https://sophieluiwi.github.io" # the base hostname & protocol for the site
og_image: /assets/img/home_pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: About me
      slug: /about-me
    - name: Blog
#   - name: This&That
#      slug: /this-and-that
    - name: Startseite
      slug: /de/
    - name: Über mich
      slug: /de/ueber-mich
    - name: Blog
      slug: /de/blog

language:
    - code: en
      name: English
    - code: de
      name: German
permalink: /:lang/:title/

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: sophie.lui.winter@gmail.com
      link: mailto:sophie.lui.winter@gmail.com

  follow:
    - name: Twitter
      link: https://twitter.com/SophieLiWi
      username: "@SophieLiWi"
    - name: LinkedIn
      link: https://www.linkedin.com/in/sophie-luise-winter-62ab211bb/
    - name: GitHub
      link: http://github.com/YourGitHubUsername

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
